### ISSUE TITLE
Documentation / Wiki?

### ISSUE THREAD

**Issue by chrisrodkey** [lucee/extension-websocket-client#1]
Good afternoon, are there any examples or reference material for how to get started with this client? I've installed the extension and I'm interested in using it but have no idea how to do it.

**Comment by powertronglobal** [comment]
usage example, please?

**Comment by chrisrodkey** [comment]
Any update on usage examples of any kind? Really just anything very simple for getting started would be helpful.

**Comment by modius** [comment]
Pretty sure the extension is a port of @isapir solution. You may find some useful documentation here in the interim:

https://github.com/isapir/lucee-websocket/wiki
https://www.youtube.com/watch?v=r2s2kGQVZqg

And general support here:
https://dev.lucee.org/c/hacking/extensions

**Comment by isapir** [comment]
@modius Actually the repo you pointed to only implements the WebSocket Server at this time, and this extension is for a WebSocket Client, so @michaeloffner might be able to shed some light on this one.

**Comment by isapir** [comment]
Side note: Java 11 introduced a new HttpClient which has built in support for WebSocket, so that might be the right path for (re)implementing this feature.
